### ISSUE TITLE
missing saxon-dom dependency

### ISSUE THREAD

**Issue by jaceko** [jmurty/java-xmlbuilder#9]
I am getting the following exception
com.jamesmurty.utils.XMLBuilderRuntimeException: net.sf.saxon.trans.DynamicError: DOMSource cannot be processed: check that saxon8-dom.jar is on the classpath
	at com.jamesmurty.utils.XMLBuilder2.wrapExceptionAsRuntimeException(XMLBuilder2.java:107)
	at com.jamesmurty.utils.XMLBuilder2.toWriter(XMLBuilder2.java:523)
	at com.jamesmurty.utils.BaseXMLBuilder.toWriter(BaseXMLBuilder.java:1251)
	at com.jamesmurty.utils.XMLBuilder2.toWriter(XMLBuilder2.java:536)
	at com.jamesmurty.utils.BaseXMLBuilder.asString(BaseXMLBuilder.java:1272)
	at com.jamesmurty.utils.XMLBuilder2.asString(XMLBuilder2.java:478)
	at com.jamesmurty.utils.BaseXMLBuilder.asString(BaseXMLBuilder.java:1310)
	at com.jamesmurty.utils.XMLBuilder2.asString(XMLBuilder2.java:464)

Adding the saxon-dom dependency to my pom file fixed the problem.

**Comment by jmurty** [comment]
Hi @jaceko your environment must be configured to use the Saxon XML library, this isn't normally the case
